import { useState } from "react";
import { useReports, useGenerateReport } from "../queries/report.queries";
import { Card }   from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { Modal }  from "../components/ui/Modal";
import { Badge }  from "../components/ui/Badge";

const TYPES   = ["COST_SUMMARY", "RESOURCE_INVENTORY"];
const FORMATS = ["PDF", "EXCEL", "CSV"];

const formatColor: Record<string, "red" | "green" | "blue"> = {
  PDF: "red", EXCEL: "green", CSV: "blue",
};

export function ReportsPage() {
  const { data: reports, isLoading }                      = useReports();
  const { mutate: generate, isLoading: generating }       = useGenerateReport();
  const [modalOpen, setModalOpen]                         = useState(false);
  const [form, setForm] = useState({ type: "COST_SUMMARY", format: "PDF", from: "", to: "" });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Reports</h1>
          <p className="text-gray-500 text-sm mt-1">Generate and download PDF, Excel, and CSV reports</p>
        </div>
        <Button onClick={() => setModalOpen(true)}>+ Generate report</Button>
      </div>

      {/* Report list */}
      {isLoading ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="h-16 animate-pulse bg-gray-100 dark:bg-gray-800 rounded-xl"/>
          ))}
        </div>
      ) : (reports ?? []).length === 0 ? (
        <Card>
          <p className="text-center text-gray-500 py-8">
            No reports generated yet. Click "Generate report" to create one.
          </p>
        </Card>
      ) : (
        <Card padding={false}>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 dark:border-gray-800">
                {["Format", "Generated by", "Created", "Download"].map((h) => (
                  <th key={h} className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
              {(reports ?? []).map((r) => (
                <tr key={r.id} className="hover:bg-gray-50 dark:hover:bg-gray-800/50">
                  <td className="px-6 py-4">
                    <Badge label={r.format} color={formatColor[r.format] ?? "gray"}/>
                  </td>
                  <td className="px-6 py-4 text-gray-500">{r.generatedBy}</td>
                  <td className="px-6 py-4 text-gray-500">
                    {new Date(r.createdAt).toLocaleString()}
                  </td>
                  <td className="px-6 py-4">
                    <a href={`/api/v1/reports/${r.id}/download`}
                      className="text-brand-600 hover:underline text-sm font-medium"
                      download>
                      Download
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      )}

      {/* Generate modal */}
      <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Generate Report"
        footer={
          <Button loading={generating}
            onClick={() => {
              generate({ ...form, from: form.from || undefined, to: form.to || undefined });
              setModalOpen(false);
            }}>
            Generate
          </Button>
        }
      >
        <div className="space-y-4">
          <div>
            <label className="text-sm font-medium text-gray-700 dark:text-gray-300 block mb-1">Report type</label>
            <select value={form.type} onChange={(e) => setForm((f) => ({ ...f, type: e.target.value }))}
              className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-700
                bg-white dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500">
              {TYPES.map((t) => <option key={t} value={t}>{t.replace(/_/g, " ")}</option>)}
            </select>
          </div>
          <div>
            <label className="text-sm font-medium text-gray-700 dark:text-gray-300 block mb-1">Format</label>
            <div className="flex gap-2">
              {FORMATS.map((f) => (
                <button key={f} onClick={() => setForm((s) => ({ ...s, format: f }))}
                  className={`px-4 py-2 rounded-lg text-sm font-medium border transition-colors
                    ${form.format === f
                      ? "bg-brand-600 text-white border-brand-600"
                      : "border-gray-300 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800"
                    }`}>
                  {f}
                </button>
              ))}
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300 block mb-1">
                From (optional)
              </label>
              <input type="date" value={form.from}
                onChange={(e) => setForm((s) => ({ ...s, from: e.target.value }))}
                className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-700
                  bg-white dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"/>
            </div>
            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300 block mb-1">
                To (optional)
              </label>
              <input type="date" value={form.to}
                onChange={(e) => setForm((s) => ({ ...s, to: e.target.value }))}
                className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-700
                  bg-white dark:bg-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500"/>
            </div>
          </div>
        </div>
      </Modal>
    </div>
  );
}